version: '3.7'

services:

  weblocacao-extensions:
    build: .
    image: flaviostutz/weblocacao-extensions
    ports:
      - 8181:80
    environment:
      - PROXY_READ_TIMEOUT=300s
      - WEEKLY_VIEW_TIME=15
      - WEEKLY2_VIEW_TIME=5
      - MONTHLY_VIEW_TIME=5
    # volumes:
    #   - /Users/flaviostutz/Documents/development/flaviostutz/weblocacao-extensions/src:/www/_www
