version: '3.7'

services:

  weblocacao-extensions:
    build: .
    image: flaviostutz/weblocacao-extensions
    ports:
      - 8181:80
    environment:
      - PROXY_READ_TIMEOUT=300s
    volumes:
      - /Users/flaviostutz/Documents/development/flaviostutz/weblocacao-extensions/src:/www/_www
